# Production Logging (Keep output clean and reduce CloudWatch ingestion costs)
logging.level.root=WARN
logging.level.com.citibike.api=INFO
logging.level.software.amazon.awssdk=ERROR

# AWS Environment Values (Passed via CDK Environment Variables)
aws.region=${AWS_REGION:us-east-1}
aws.dynamodb.table-name=${DYNAMODB_TABLE_NAME}

# TODO: Add frontend domain name to cors allow list