# Logging Configuration for Local Debugging
logging.level.root=INFO
logging.level.com.citibike.api=DEBUG
logging.level.software.amazon.awssdk=INFO

# Local AWS & DynamoDB Overrides
aws.region=us-east-1
aws.dynamodb.endpoint-override=http://localhost:8000
aws.dynamodb.table-name=citibike-station-status-local

# Dummy credentials required by local DynamoDB Docker container
aws.dynamodb.access-key-id=fakeAccessKeyId
aws.dynamodb.secret-access-key=fakeSecretAccessKey