# Logging Configuration
logging.level.root=INFO
logging.level.com.citibike.api=INFO
logging.level.software.amazon.awssdk=WARN

# AWS Environment Values (Passed via CDK Environment Variables)
aws.region=${AWS_REGION:us-east-1}
aws.dynamodb.table-name=${DYNAMODB_TABLE_NAME}

# Dev ALB / CloudFront domain or local dev machine IP
cors.allowed-origins=${FRONTEND_URL:http://localhost:5173}